// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: weave.proto

package weave

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type FieldIndex struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Unique               *bool    `protobuf:"varint,2,opt,name=unique" json:"unique,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldIndex) Reset()         { *m = FieldIndex{} }
func (m *FieldIndex) String() string { return proto.CompactTextString(m) }
func (*FieldIndex) ProtoMessage()    {}
func (*FieldIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_weave_ec8ab4aca2804447, []int{0}
}
func (m *FieldIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldIndex.Unmarshal(m, b)
}
func (m *FieldIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldIndex.Marshal(b, m, deterministic)
}
func (dst *FieldIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldIndex.Merge(dst, src)
}
func (m *FieldIndex) XXX_Size() int {
	return xxx_messageInfo_FieldIndex.Size(m)
}
func (m *FieldIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldIndex.DiscardUnknown(m)
}

var xxx_messageInfo_FieldIndex proto.InternalMessageInfo

func (m *FieldIndex) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *FieldIndex) GetUnique() bool {
	if m != nil && m.Unique != nil {
		return *m.Unique
	}
	return false
}

var E_Index = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldIndex)(nil),
	Field:         65021,
	Name:          "weave.index",
	Tag:           "bytes,65021,opt,name=index",
	Filename:      "weave.proto",
}

func init() {
	proto.RegisterType((*FieldIndex)(nil), "weave.FieldIndex")
	proto.RegisterExtension(E_Index)
}

func init() { proto.RegisterFile("weave.proto", fileDescriptor_weave_ec8ab4aca2804447) }

var fileDescriptor_weave_ec8ab4aca2804447 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x4f, 0x4d, 0x2c,
	0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0xa4, 0x14, 0xd2, 0xf3, 0xf3,
	0xd3, 0x73, 0x52, 0xf5, 0xc1, 0x82, 0x49, 0xa5, 0x69, 0xfa, 0x29, 0xa9, 0xc5, 0xc9, 0x45, 0x99,
	0x05, 0x25, 0xf9, 0x45, 0x10, 0x85, 0x4a, 0x16, 0x5c, 0x5c, 0x6e, 0x99, 0xa9, 0x39, 0x29, 0x9e,
	0x79, 0x29, 0xa9, 0x15, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x18, 0x17, 0x5b, 0x69, 0x5e, 0x66, 0x61, 0x69, 0xaa, 0x04,
	0x93, 0x02, 0xa3, 0x06, 0x47, 0x10, 0x94, 0x67, 0xe5, 0xc1, 0xc5, 0x9a, 0x09, 0xd6, 0x24, 0xab,
	0x07, 0xb1, 0x45, 0x0f, 0x66, 0x8b, 0x1e, 0xd8, 0x44, 0xff, 0x82, 0x92, 0xcc, 0xfc, 0xbc, 0x62,
	0x89, 0xbf, 0xbf, 0x99, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x04, 0xf5, 0x20, 0x0e, 0x44, 0x58, 0x17,
	0x04, 0x31, 0xc0, 0x89, 0x3d, 0x0a, 0xe2, 0x5c, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71, 0xf1,
	0xda, 0x2f, 0xc3, 0x00, 0x00, 0x00,
}
