// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test.proto

package blog

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/lehajam/protoc-gen-weave/weave"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Blog) Validate() error {
	return nil
}
func (this *Post) Validate() error {
	return nil
}
