// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test.proto

package blog

import (
	"testing"

	"github.com/stretchr/testify/require"

	_ "github.com/gogo/protobuf/gogoproto"
	_ "github.com/mwitkow/go-proto-validators"

	"github.com/iov-one/weave/crypto"
	github_com_iov_one_weave_orm "github.com/iov-one/weave/orm"
	"github.com/jinzhu/copier"
)

func BenchmarkBlogCopy_Manual(b *testing.B) {
	var authors [][]byte
	for index := 0; index < 100; index++ {
		authors = append(authors, crypto.GenPrivKeyEd25519().PublicKey().Address())
	}

	var blog github_com_iov_one_weave_orm.CloneableData
	blog = &Blog{
		Title:       "this is a blog title",
		NumArticles: 1,
		Authors:     authors,
	}

	b.ResetTimer()
	for index := 0; index < b.N; index++ {
		cpy := blog.Copy()
		require.Equal(b, blog, cpy)
	}
}

func BenchmarkBlogCopy_Copier(b *testing.B) {
	var authors [][]byte
	for index := 0; index < 100; index++ {
		authors = append(authors, crypto.GenPrivKeyEd25519().PublicKey().Address())
	}

	blog := Blog{
		Title:       "this is a blog title",
		NumArticles: 1,
		Authors:     authors,
	}

	b.ResetTimer()
	for index := 0; index < b.N; index++ {
		var cpy Blog
		copier.Copy(&cpy, &blog)
		require.Equal(b, blog, cpy)
	}
}
