// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test.proto

package blog

import fmt "fmt"
import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/gogo/protobuf/proto"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/lehajam/protoc-gen-weave/x/bucket"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Blog) Validate() error {
	if !(len(this.Title) < 100) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must length be less than '100'`, this.Title))
	}
	if len(this.Authors) < 1 {
		return github_com_mwitkow_go_proto_validators.FieldError("Authors", fmt.Errorf(`value '%v' must contain at least 1 elements`, this.Authors))
	}
	if len(this.Authors) > 10 {
		return github_com_mwitkow_go_proto_validators.FieldError("Authors", fmt.Errorf(`value '%v' must contain at most 10 elements`, this.Authors))
	}
	if !(this.NumArticles > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("NumArticles", fmt.Errorf(`value '%v' must be greater than '0'`, this.NumArticles))
	}
	return nil
}
func (this *Post) Validate() error {
	if !(len(this.Title) < 100) {
		return github_com_mwitkow_go_proto_validators.FieldError("Title", fmt.Errorf(`value '%v' must length be less than '100'`, this.Title))
	}
	if !(this.CreationBlock > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("CreationBlock", fmt.Errorf(`value '%v' must be greater than '0'`, this.CreationBlock))
	}
	if !(len(this.Text) < 20000) {
		return github_com_mwitkow_go_proto_validators.FieldError("Text", fmt.Errorf(`value '%v' must length be less than '20000'`, this.Text))
	}
	return nil
}
